/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eb814f6f-c290-4bf8-b2b9-4ee372fe53b8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wKcnt9PHt",
    "aws_user_pools_web_client_id": "4h8ungbbde1pui5g5frosc0e39",
    "oauth": {}
};

 
export default awsmobile;
